#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# Implementation Pipeline — static, testable, lintable
#
# Usage: pipeline.sh <config-file>
#
# The config file is a shell-sourceable file that defines:
#   REPO, WORKTREE_BASE, OWNER_REPO, AI_REVIEW_PROVIDER, AI_REVIEW_API_BASE, BASE_BRANCH, MERGE_STRATEGY,
#   REVIEW_LOOP_COUNT, TIMEOUT_IMPL, TIMEOUT_REVIEW, TIMEOUT_BOT, TIMEOUT_CI,
#   ISSUES (array), BRANCHES (array)
#
# Optional config overrides (also settable via environment):
#   SKIP_REVIEW, SKIP_BOT, SKIP_SCOPE_GATE, FORCE_ISSUES, NO_MERGE
#
# This script is NOT generated by the AI agent. The agent's only job is to
# write the config file and invoke this script. All pipeline logic lives here.
# ═══════════════════════════════════════════════════════════════════════════════
set -uo pipefail

readonly VERSION="1.0.0"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR

# ── Config loading and validation ────────────────────────────────────────────

usage() {
  cat >&2 <<EOF
Usage: $(basename "$0") <config-file>

The config file must define:
  REPO             — path to canonical repo checkout
  WORKTREE_BASE    — base path for worktrees
  OWNER_REPO       — GitHub owner/repo (e.g. "org/repo-name")
  AI_REVIEW_PROVIDER  — ai-pr-review-loop provider (coderabbit or ghe-pr-bot)
  AI_REVIEW_API_BASE  — GitHub API base URL for the provider
  ISSUES           — bash array of issue numbers
  BRANCHES         — bash array of branch names (same length as ISSUES)

Optional (have defaults):
  BASE_BRANCH          — base branch (auto-detected if unset)
  MERGE_STRATEGY       — squash (default), merge, rebase
  REVIEW_LOOP_COUNT    — max bot review rounds (default: 5)
  TIMEOUT_IMPL         — implementation timeout in seconds (default: 2400)
  TIMEOUT_REVIEW       — self-review timeout in seconds (default: 1200)
  TIMEOUT_BOT          — bot review timeout in seconds (default: 7200)
  TIMEOUT_CI           — CI polling timeout in seconds (default: 600)
  TIMEOUT_GATE         — scope gate timeout in seconds (default: 120)
  LOCAL_CODERABBIT_PRECHECK — 1 to run local CodeRabbit CLI before PR for coderabbit provider (default: 1)
  SKIP_REVIEW          — 1 to skip self-review phase (default: 0)
  SKIP_BOT             — 1 to skip bot review phase (default: 0)
  SKIP_SCOPE_GATE      — 1 to skip scope gate (default: 0)
  FORCE_ISSUES         — comma-separated issues to bypass scope gate
  NO_MERGE             — 1 to stop after review without merging (default: 0)
  LOG_DIR              — override log directory (default: /tmp/impl-pipeline-<timestamp>)
  CONTINUE_ON_FAILURE  — set 1 only for independent best-effort batches (default: 0)
  IMPL_SKILL           — skill path for implementation (default: design-first-implementation)
  REVIEW_SKILL         — skill path for self-review (default: targeted-pr-review)
  BOT_SKILL            — skill path for bot review (default: ai-pr-review-loop)
  GHE_API              — deprecated fallback for AI_REVIEW_API_BASE
  EXTRA_IMPL_CONTEXT   — extra text appended to implementation prompt
EOF
  exit 1
}

validate_config() {
  local errors=0

  # Required fields
  for var in REPO WORKTREE_BASE OWNER_REPO AI_REVIEW_PROVIDER AI_REVIEW_API_BASE; do
    if [ -z "${!var:-}" ]; then
      echo "ERROR: Required config variable $var is not set." >&2
      errors=$((errors + 1))
    fi
  done

  # Arrays must exist and be non-empty
  if [ ${#ISSUES[@]} -eq 0 ]; then
    echo "ERROR: ISSUES array is empty." >&2
    errors=$((errors + 1))
  fi
  if [ ${#BRANCHES[@]} -eq 0 ]; then
    echo "ERROR: BRANCHES array is empty." >&2
    errors=$((errors + 1))
  fi
  if [ ${#ISSUES[@]} -ne ${#BRANCHES[@]} ]; then
    echo "ERROR: ISSUES (${#ISSUES[@]}) and BRANCHES (${#BRANCHES[@]}) arrays must be same length." >&2
    errors=$((errors + 1))
  fi

  # Repo must exist
  if [ ! -d "$REPO/.git" ] && [ ! -f "$REPO/.git" ]; then
    echo "ERROR: REPO ($REPO) is not a git repository." >&2
    errors=$((errors + 1))
  fi

  # MERGE_STRATEGY must be valid
  case "${MERGE_STRATEGY:-squash}" in
    squash|merge|rebase) ;;
    *) echo "ERROR: MERGE_STRATEGY must be squash, merge, or rebase (got: $MERGE_STRATEGY)" >&2; errors=$((errors + 1)) ;;
  esac

  # AI_REVIEW_PROVIDER must be valid
  case "${AI_REVIEW_PROVIDER:-}" in
    coderabbit|ghe-pr-bot) ;;
    *) echo "ERROR: AI_REVIEW_PROVIDER must be coderabbit or ghe-pr-bot (got: ${AI_REVIEW_PROVIDER:-})" >&2; errors=$((errors + 1)) ;;
  esac

  # Boolean toggles must be 0 or 1
  for var in SKIP_REVIEW SKIP_BOT SKIP_SCOPE_GATE NO_MERGE CONTINUE_ON_FAILURE; do
    if [ "${!var:-0}" != "0" ] && [ "${!var:-0}" != "1" ]; then
      echo "ERROR: $var must be 0 or 1 (got: ${!var:-})" >&2
      errors=$((errors + 1))
    fi
  done

  # Timeouts must be positive integers
  for var in TIMEOUT_IMPL TIMEOUT_REVIEW TIMEOUT_BOT TIMEOUT_CI TIMEOUT_GATE; do
    if ! [[ "${!var:-0}" =~ ^[0-9]+$ ]] || [ "${!var:-0}" -eq 0 ]; then
      echo "ERROR: $var must be a positive integer (got: ${!var:-})" >&2
      errors=$((errors + 1))
    fi
  done

  # pi must be available
  if ! command -v pi >/dev/null 2>&1; then
    echo "ERROR: 'pi' command not found in PATH." >&2
    errors=$((errors + 1))
  fi

  # gh must be available
  if ! command -v gh >/dev/null 2>&1; then
    echo "ERROR: 'gh' command not found in PATH." >&2
    errors=$((errors + 1))
  fi

  if [ $errors -gt 0 ]; then
    echo "Config validation failed with $errors error(s)." >&2
    return 1
  fi
  return 0
}

# ── Load config ──────────────────────────────────────────────────────────────

if [ $# -lt 1 ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  usage
fi

CONFIG_FILE="$1"
if [ ! -f "$CONFIG_FILE" ]; then
  echo "ERROR: Config file not found: $CONFIG_FILE" >&2
  exit 1
fi

# Initialize arrays before sourcing (prevents "unbound variable" with set -u)
ISSUES=()
BRANCHES=()

# shellcheck source=/dev/null
source "$CONFIG_FILE"

# Apply defaults for optional fields
BASE_BRANCH="${BASE_BRANCH:-}"
if [ -z "$BASE_BRANCH" ]; then
  BASE_BRANCH=$(git -C "$REPO" symbolic-ref --short refs/remotes/origin/HEAD 2>/dev/null | sed 's#^origin/##' || true)
fi
BASE_BRANCH="${BASE_BRANCH:-main}"
MERGE_STRATEGY="${MERGE_STRATEGY:-squash}"
REVIEW_LOOP_COUNT="${REVIEW_LOOP_COUNT:-5}"
TIMEOUT_IMPL="${TIMEOUT_IMPL:-2400}"
TIMEOUT_REVIEW="${TIMEOUT_REVIEW:-1200}"
TIMEOUT_BOT="${TIMEOUT_BOT:-7200}"
TIMEOUT_CI="${TIMEOUT_CI:-600}"
TIMEOUT_GATE="${TIMEOUT_GATE:-120}"
LOCAL_CODERABBIT_PRECHECK="${LOCAL_CODERABBIT_PRECHECK:-1}"
SKIP_REVIEW="${SKIP_REVIEW:-0}"
SKIP_BOT="${SKIP_BOT:-0}"
SKIP_SCOPE_GATE="${SKIP_SCOPE_GATE:-0}"
FORCE_ISSUES="${FORCE_ISSUES:-}"
NO_MERGE="${NO_MERGE:-0}"
CONTINUE_ON_FAILURE="${CONTINUE_ON_FAILURE:-0}"
IMPL_SKILL="${IMPL_SKILL:-design-first-implementation}"
REVIEW_SKILL="${REVIEW_SKILL:-targeted-pr-review}"
AI_REVIEW_PROVIDER="${AI_REVIEW_PROVIDER:-ghe-pr-bot}"
AI_REVIEW_API_BASE="${AI_REVIEW_API_BASE:-${GHE_API:-}}"
case "$AI_REVIEW_PROVIDER" in
  coderabbit)
    AI_REVIEW_API_BASE="${AI_REVIEW_API_BASE:-https://api.github.com}"
    ;;
  ghe-pr-bot)
    AI_REVIEW_API_BASE="${AI_REVIEW_API_BASE:-https://github.concur.com/api/v3}"
    ;;
  *)
    :
    ;;
esac
BOT_SKILL="${BOT_SKILL:-ai-pr-review-loop}"
EXTRA_IMPL_CONTEXT="${EXTRA_IMPL_CONTEXT:-}"

# Resolve skill paths: if not absolute, look in the skill directory's parent
resolve_skill() {
  local skill="$1"
  if [[ "$skill" == /* ]]; then
    echo "$skill"
  elif [ -d "$SCRIPT_DIR/../$skill" ]; then
    echo "$SCRIPT_DIR/../$skill"
  elif [ -d "$HOME/.pi/agent/skills/$skill" ]; then
    echo "$HOME/.pi/agent/skills/$skill"
  else
    echo "$skill"  # Let pi resolve it
  fi
}

IMPL_SKILL_PATH="$(resolve_skill "$IMPL_SKILL")"
REVIEW_SKILL_PATH="$(resolve_skill "$REVIEW_SKILL")"
BOT_SKILL_PATH="$(resolve_skill "$BOT_SKILL")"

# Set up log directory
if [ -z "${LOG_DIR:-}" ]; then
  LOG_DIR="/tmp/impl-pipeline-$(date +%s)"
fi
mkdir -p "$LOG_DIR"

# Validate
if ! validate_config; then
  exit 1
fi

# ── Process management ───────────────────────────────────────────────────────

CHILD_PIDS=()

cleanup() {
  local exit_code=$?
  log "Pipeline interrupted (exit=$exit_code) — killing child processes"
  for pid in "${CHILD_PIDS[@]:-}"; do
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
      # Try process group first, fall back to single PID
      kill -TERM -- -"$pid" 2>/dev/null || kill -TERM "$pid" 2>/dev/null || true
      log "  Sent TERM to PID $pid"
    fi
  done
  # Grace period then force kill
  sleep 5
  for pid in "${CHILD_PIDS[@]:-}"; do
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
      kill -9 "$pid" 2>/dev/null || true
      log "  Force-killed PID $pid"
    fi
  done
  write_status "killed"
  log "Cleanup complete. Log: $LOG_DIR/loop.log"
  exit "$exit_code"
}
trap cleanup INT TERM

# ── Utility functions ────────────────────────────────────────────────────────

log() {
  echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*" | tee -a "$LOG_DIR/loop.log"
}

write_status() {
  local state="$1"
  cat > "$LOG_DIR/status.json.tmp" <<EOF
{
  "pipeline_state": "$state",
  "version": "$VERSION",
  "config_file": "$CONFIG_FILE",
  "started_at": "$PIPELINE_START",
  "current_issue": ${CURRENT_ISSUE:-null},
  "current_phase": "${CURRENT_PHASE:-}",
  "current_pr": ${CURRENT_PR:-null},
  "current_agent_pid": ${CURRENT_AGENT_PID:-null},
  "issues_completed": [$(IFS=,; echo "${ISSUES_COMPLETED[*]:-}")],
  "issues_skipped": [$(IFS=,; echo "${ISSUES_SKIPPED[*]:-}")],
  "issues_remaining": [$(IFS=,; echo "${ISSUES_REMAINING[*]:-}")],
  "last_update": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF
  mv "$LOG_DIR/status.json.tmp" "$LOG_DIR/status.json"
}

check_control() {
  if [ -f "$LOG_DIR/control" ]; then
    local cmd
    cmd=$(cat "$LOG_DIR/control" 2>/dev/null || echo "")
    : > "$LOG_DIR/control"
    echo "$cmd"
  else
    echo ""
  fi
}

wait_for_handoff() {
  local handoff_file="$1"
  local timeout="$2"
  local agent_pid="${3:-}"
  local elapsed=0

  while [ $elapsed -lt "$timeout" ]; do
    # File must exist AND be non-empty (guards against partial writes)
    if [ -f "$handoff_file" ] && [ -s "$handoff_file" ]; then
      return 0
    fi

    # Dead-PID detection
    if [ -n "$agent_pid" ] && ! kill -0 "$agent_pid" 2>/dev/null; then
      # Grace period for filesystem flush
      sleep 5
      if [ -f "$handoff_file" ] && [ -s "$handoff_file" ]; then
        return 0
      fi
      log "    Agent PID $agent_pid died without writing handoff"
      return 1
    fi

    sleep 30
    elapsed=$((elapsed + 30))

    # Heartbeat every 5 minutes
    if (( elapsed % 300 == 0 )); then
      log "    Waiting for handoff... ${elapsed}s / ${timeout}s"
    fi
  done

  # Final check
  [ -f "$handoff_file" ] && [ -s "$handoff_file" ]
}

kill_agent() {
  local pid="$1"
  if kill -0 "$pid" 2>/dev/null; then
    kill -TERM "$pid" 2>/dev/null || true
    sleep 3
    if kill -0 "$pid" 2>/dev/null; then
      kill -9 "$pid" 2>/dev/null || true
    fi
  fi
}

extract_pr_number() {
  local worktree="$1"
  local handoff="${2:-}"
  local pr_num=""

  # Authoritative: gh CLI on the branch
  pr_num=$(cd "$worktree" && gh pr view --json number -q .number 2>/dev/null) || true
  if [ -n "$pr_num" ] && [ "$pr_num" != "null" ]; then
    echo "$pr_num"
    return 0
  fi

  # Fallback: parse handoff
  if [ -n "$handoff" ] && [ -f "$handoff" ]; then
    pr_num=$(grep -oP '(?:PR\s*#|pull/|number:\s*)(\d+)' "$handoff" 2>/dev/null | grep -oP '\d+' | head -1) || true
    if [ -n "$pr_num" ]; then
      echo "$pr_num"
      return 0
    fi
  fi

  return 1
}

verify_local_coderabbit_precheck() {
  local handoff="$1"

  if [ "${AI_REVIEW_PROVIDER:-}" != "coderabbit" ] || [ "${LOCAL_CODERABBIT_PRECHECK:-1}" != "1" ]; then
    return 0
  fi

  if [ ! -s "$handoff" ]; then
    log "  ERROR: Missing implementation handoff; cannot verify local CodeRabbit precheck."
    return 1
  fi

  if ! grep -Eiq "local[[:space:]-]+coderabbit|coderabbit review" "$handoff"; then
    log "  ERROR: Implementation handoff does not document the required local CodeRabbit precheck."
    return 1
  fi

  if grep -Eiq "coderabbit.*(not run|skipped|unavailable|failed|error)|doctor.*(fail|error)|precheck.*(not run|skipped|failed|unavailable)" "$handoff"; then
    log "  ERROR: Local CodeRabbit precheck is documented as missing/failed."
    return 1
  fi

  if ! grep -Eiq "(0 findings|findings:[[:space:]]*0|findings[[:space:]]*\|?[[:space:]]*0|all (findings )?addressed|addressed in-place|clean|review completed.*0)" "$handoff"; then
    log "  ERROR: Local CodeRabbit precheck lacks a clear clean/all-addressed result."
    return 1
  fi

  log "  Local CodeRabbit precheck documented ✓"
  return 0
}

wait_for_ci() {
  local pr="$1"
  local timeout="${2:-$TIMEOUT_CI}"
  local elapsed=0

  log "    Polling CI (max ${timeout}s)..." >&2
  while [ $elapsed -lt "$timeout" ]; do
    local pending
    pending=$(gh pr view "$pr" --json statusCheckRollup -q \
      '[.statusCheckRollup[] | select((.status != null and .status != "COMPLETED") or (.state != null and (.state == "PENDING" or .state == "EXPECTED"))) ] | length' 2>/dev/null) || true

    if [ "${pending:-999}" = "0" ]; then
      local failures
      failures=$(gh pr view "$pr" --json statusCheckRollup -q \
        '[.statusCheckRollup[] | select((.conclusion != null and (.conclusion == "FAILURE" or .conclusion == "CANCELLED" or .conclusion == "TIMED_OUT" or .conclusion == "ACTION_REQUIRED")) or (.state != null and (.state == "FAILURE" or .state == "ERROR"))) ] | length' 2>/dev/null) || true
      echo "${failures:-0}"
      return 0
    fi

    sleep 30
    elapsed=$((elapsed + 30))
    if (( elapsed % 120 == 0 )); then
      log "    CI: ${pending:-?} checks pending (${elapsed}s)" >&2
    fi
  done

  log "    CI timed out after ${timeout}s" >&2
  echo "timeout"
  return 1
}

cleanup_worktree() {
  local wt_path="$1"
  if [ -d "$wt_path" ]; then
    cd "$REPO" || return
    git worktree remove "$wt_path" --force 2>/dev/null || rm -rf "$wt_path"
    git worktree prune 2>/dev/null || true
  fi
}

handle_issue_failure() {
  local issue="$1"
  local reason="$2"

  ISSUES_SKIPPED+=("$issue")

  if [ "$CONTINUE_ON_FAILURE" = "1" ]; then
    log "  Continuing after #$issue failure because CONTINUE_ON_FAILURE=1: $reason"
    return 0
  fi

  CURRENT_PHASE="blocked"
  PIPELINE_TERMINAL_STATE="blocked"
  log "  Stopping before the next issue. Sequential mode requires #$issue to be resolved first: $reason"
  write_status "blocked"
  return 1
}

# ── Prompt generators ────────────────────────────────────────────────────────
# These functions produce the prompt files. They are the ONLY place where
# prompt text lives. The AI agent cannot modify pipeline behavior because
# it never writes these — the static script does.

generate_gate_prompt() {
  local issue="$1" gate_file="$2"
  cat <<EOF
You are evaluating whether GitHub issue #$issue is appropriately scoped for a single
implementation + review pipeline pass.

Read the issue: \`gh issue view $issue --json body,title\`

Score using the Reviewability Risk Score (0-14):

Boundary clarity (0-4): subsystems touched, existing-vs-new code, contract boundaries.
Scope firmness (0-4): acceptance criteria count/quality, stopping point clarity, adjacent temptation.
Review difficulty (0-4): diff size estimate, behavioral change count, domain knowledge needed.
Dependency risk (0-2): prerequisites in $BASE_BRANCH, test isolation.

Thresholds: 0-4=proceed, 5-7=proceed-with-warning, 8+=skip, dependency=2=blocker.

Write EXACTLY ONE LINE to $gate_file:
- "proceed" if score 0-4
- "proceed-with-warning:<score>; <highest factors>" if score 5-7
- "skip:<score>; <reason + split recommendation>" if score 8+
- "blocker:<what prerequisite is missing>" if dependency=2

Do not write anything else. Do not ask questions. Do not spawn another pi instance.
EOF
}

generate_impl_prompt() {
  local issue="$1" worktree="$2" branch="$3" handoff="$4" scope_warning="${5:-}"

  echo "You are implementing GitHub issue #${issue}."
  echo ""
  echo "Working directory: ${worktree}"
  echo "Branch: ${branch}"

  if [ -n "$scope_warning" ]; then
    echo ""
    echo "SCOPE WARNING: ${scope_warning}"
    echo "Stay focused on ONLY what the issue acceptance criteria require. Do not fix adjacent code,"
    echo "refactor existing patterns, or expand scope beyond the explicit criteria. If you notice"
    echo "something that needs fixing but is not in the acceptance criteria, note it in the PR body"
    echo "as a follow-up - do not implement it."
  fi

  echo ""
  echo "Instructions:"
  echo "1. Read the issue: gh issue view ${issue} --json body,title"
  echo "2. Apply the design-first-implementation skill (full workflow if edge cases exist)"
  echo "3. Implement following all repository AGENTS.md rules"
  echo "4. Run make check (or the repo equivalent validation) and ensure it passes"
  if [ "${AI_REVIEW_PROVIDER:-}" = "coderabbit" ] && [ "${LOCAL_CODERABBIT_PRECHECK:-1}" = "1" ]; then
    echo "5. Commit all changes with a descriptive message referencing #${issue}"
    echo "6. Before pushing or opening a PR, run the local CodeRabbit CLI precheck against the committed diff:"
    echo "   - Verify availability with: command -v coderabbit && coderabbit doctor"
    echo "   - Run: coderabbit review --agent --type committed --base ${BASE_BRANCH}"
    echo "   - Then inspect findings with: coderabbit review findings"
    echo "   - Treat verified functional/security/correctness findings as pre-PR defects: fix them, add/update tests, rerun validation, amend/commit, and rerun the local CodeRabbit review until no real actionable findings remain."
    echo "   - For false-positive, stale, or explicitly out-of-scope findings, record the rationale in the PR body and handoff; do not churn low-value suggestions."
    echo "   - If the CLI is unavailable or authentication/service is down, stop and write a blocker handoff; do not open the PR without local CodeRabbit unless the user explicitly overrides LOCAL_CODERABBIT_PRECHECK."
    echo "7. Push the branch to origin"
    echo "8. Open a non-draft PR targeting ${BASE_BRANCH} with title and body referencing #${issue}. The PR body must include a 'Local CodeRabbit Precheck' section with command/result/finding disposition."
    echo "9. Write a handoff to ${handoff} with: PR number, head SHA, validation results, local CodeRabbit precheck command/result/finding disposition, files changed"
  else
    echo "5. Commit all changes with a descriptive message referencing #${issue}"
    echo "6. Push the branch to origin"
    echo "7. Open a non-draft PR targeting ${BASE_BRANCH} with title and body referencing #${issue}"
    echo "8. Write a handoff to ${handoff} with: PR number, head SHA, validation results, files changed"
  fi
  echo ""
  echo "Do NOT ask for clarification - implement based on the issue acceptance criteria."
  echo "Do NOT spawn another pi instance."
  echo "If the issue references prerequisites, confirm they are in ${BASE_BRANCH} before starting."

  if [ -n "${EXTRA_IMPL_CONTEXT:-}" ]; then
    echo ""
    echo "$EXTRA_IMPL_CONTEXT"
  fi
}

generate_review_prompt() {
  local pr="$1" worktree="$2" branch="$3" handoff="$4"
  cat <<EOF
Run a targeted PR review of PR #$pr.

Working directory: $worktree
Branch: $branch

Instructions:
1. Use the targeted-pr-review skill for multi-dimension review
2. Fix actionable defects (real bugs, missing tests, contract violations)
3. Run \`make check\` after fixes
4. Commit and push fixes
5. Write handoff to $handoff with: findings, fixes, head SHA, validation result

Do NOT spawn another pi instance.
EOF
}

generate_bot_prompt() {
  local pr="$1" worktree="$2" session_id="$3" handoff="$4"
  cat <<EOF
/skill:ai-pr-review-loop worker mode

You are the worker pi instance. Do not spawn another pi instance.

Provider: $AI_REVIEW_PROVIDER

Task: run $REVIEW_LOOP_COUNT preflight-first AI PR review loop(s) for PR #$pr and address actionable items.

Before triggering remote CodeRabbit for coderabbit provider, verify the PR body documents a Local CodeRabbit Precheck. If the precheck is missing, run `coderabbit doctor` and `coderabbit review --agent --type committed --base $BASE_BRANCH` locally as a fallback, fix real findings, update the PR body/comment with the result, and note in HANDOFF that the required pre-PR check was recovered post-PR. Do not treat this fallback as a substitute for future implementation agents running it before PR creation.

Inputs:
- WORKTREE: $worktree
- PR: $pr
- OWNER_REPO: $OWNER_REPO
- PROVIDER: $AI_REVIEW_PROVIDER
- API_BASE: $AI_REVIEW_API_BASE
- SESSION_ID: $session_id
- LOG: $LOG_DIR/${session_id}.log
- HANDOFF: $handoff
EOF
}

# ── Pipeline state ───────────────────────────────────────────────────────────

PIPELINE_START="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
ISSUES_COMPLETED=()
ISSUES_SKIPPED=()
ISSUES_REMAINING=("${ISSUES[@]}")
CURRENT_ISSUE=""
CURRENT_PHASE=""
CURRENT_PR=""
CURRENT_AGENT_PID=""
PIPELINE_TERMINAL_STATE="completed"

write_status "running"

log "═══════════════════════════════════════════════════════════════"
log "Implementation Pipeline v${VERSION}"
log "═══════════════════════════════════════════════════════════════"
log "Config:    $CONFIG_FILE"
log "Repo:      $REPO"
log "Issues:    ${ISSUES[*]}"
log "Strategy:  $MERGE_STRATEGY"
log "Timeouts:  impl=${TIMEOUT_IMPL}s rev=${TIMEOUT_REVIEW}s bot=${TIMEOUT_BOT}s ci=${TIMEOUT_CI}s"
log "Flags:     review=${SKIP_REVIEW:+SKIP}${SKIP_REVIEW:-on} bot=${SKIP_BOT:+SKIP}${SKIP_BOT:-on} gate=${SKIP_SCOPE_GATE:+SKIP}${SKIP_SCOPE_GATE:-on} merge=${NO_MERGE:+NO}${NO_MERGE:-on} continue_on_failure=$CONTINUE_ON_FAILURE local_coderabbit=$LOCAL_CODERABBIT_PRECHECK"
log "Log dir:   $LOG_DIR"
log "═══════════════════════════════════════════════════════════════"

# ── Main loop ────────────────────────────────────────────────────────────────

for i in "${!ISSUES[@]}"; do
  ISSUE="${ISSUES[$i]}"
  BRANCH="${BRANCHES[$i]}"
  WORKTREE="$WORKTREE_BASE/$BRANCH"
  CURRENT_ISSUE="$ISSUE"
  CURRENT_PR=""
  SCOPE_WARNING=""

  # Remove from remaining
  ISSUES_REMAINING=("${ISSUES_REMAINING[@]:1}")

  # ── Control check ─────────────────────────────────────
  CTRL=$(check_control)
  case "$CTRL" in
    abort)
      log "ABORT received. Stopping."
      write_status "aborted"
      break
      ;;
    pause)
      log "PAUSE received. Waiting for 'resume'..."
      while true; do
        sleep 10
        CTRL=$(check_control)
        [ "$CTRL" = "resume" ] && break
        [ "$CTRL" = "abort" ] && { log "ABORT during pause."; write_status "aborted"; exit 0; }
      done
      log "Resumed."
      ;;
    skip)
      log "SKIP received. Skipping #$ISSUE."
      ISSUES_SKIPPED+=("$ISSUE")
      continue
      ;;
  esac

  log ""
  log "══════════════════════════════════════"
  log "ISSUE #$ISSUE — $BRANCH"
  log "══════════════════════════════════════"

  # ── Phase 1: Worktree setup ───────────────────────────
  CURRENT_PHASE="worktree-setup"
  write_status "running"
  log "[1/5] Worktree setup"
  if ! cd "$REPO"; then
    handle_issue_failure "$ISSUE" "cannot cd to repo $REPO" || break
    continue
  fi
  git fetch origin "$BASE_BRANCH" --quiet

  if [ -d "$WORKTREE" ]; then
    # Check for existing PR (don't destroy in-progress work)
    EXISTING_PR=$(cd "$WORKTREE" && gh pr view --json number -q .number 2>/dev/null) || true
    if [ -n "$EXISTING_PR" ] && [ "$EXISTING_PR" != "null" ]; then
      log "  PR #$EXISTING_PR already exists for $BRANCH."
      handle_issue_failure "$ISSUE" "existing open PR #$EXISTING_PR must be merged or closed before continuing" || break
      continue
    fi
    if ! cd "$WORKTREE"; then
      handle_issue_failure "$ISSUE" "cannot cd to existing worktree $WORKTREE" || break
      continue
    fi
    git fetch origin "$BASE_BRANCH" --quiet
    git reset --hard "origin/$BASE_BRANCH"
  elif [ -x "$REPO/scripts/setup-worktree.sh" ]; then
    "$REPO/scripts/setup-worktree.sh" "$BRANCH" || {
      log "  setup-worktree.sh failed, creating manually"
      git branch -D "$BRANCH" 2>/dev/null || true
      git worktree add "$WORKTREE" -b "$BRANCH" "origin/$BASE_BRANCH"
      cd "$WORKTREE" && [ -f Makefile ] && make sync
    }
  else
    git branch -D "$BRANCH" 2>/dev/null || true
    git worktree add "$WORKTREE" -b "$BRANCH" "origin/$BASE_BRANCH"
    cd "$WORKTREE" && [ -f Makefile ] && make sync
  fi

  if ! cd "$WORKTREE"; then
    handle_issue_failure "$ISSUE" "worktree setup did not produce $WORKTREE" || break
    continue
  fi
  log "  Ready: $WORKTREE"

  # ── Phase 0: Scope gate ───────────────────────────────
  if [ "$SKIP_SCOPE_GATE" = "1" ]; then
    log "[0] Scope gate: SKIPPED"
  elif echo ",$FORCE_ISSUES," | grep -q ",$ISSUE,"; then
    log "[0] Scope gate: BYPASSED (FORCE_ISSUES)"
  else
    CURRENT_PHASE="scope-gate"
    write_status "running"
    log "[0] Scope gate"
    GATE_ID="gate-${ISSUE}-$(date +%s)"
    GATE_FILE="/tmp/${GATE_ID}-verdict.txt"
    GATE_PROMPT_FILE="$LOG_DIR/${GATE_ID}-prompt.md"

    generate_gate_prompt "$ISSUE" "$GATE_FILE" > "$GATE_PROMPT_FILE"

    cd "$WORKTREE" || continue
    nohup pi --approve \
      --session-id "$GATE_ID" \
      -p "@$GATE_PROMPT_FILE" \
      > "$LOG_DIR/${GATE_ID}.log" 2>&1 &
    GATE_PID=$!
    CHILD_PIDS+=("$GATE_PID")

    if ! wait_for_handoff "$GATE_FILE" "$TIMEOUT_GATE" "$GATE_PID"; then
      log "  Gate timed out. Proceeding by default."
      kill_agent "$GATE_PID"
    else
      GATE_VERDICT=$(head -1 "$GATE_FILE" 2>/dev/null | tr -d '\n')
      case "$GATE_VERDICT" in
        proceed)
          log "  PROCEED"
          ;;
        proceed-with-warning:*)
          SCOPE_WARNING="${GATE_VERDICT#proceed-with-warning:}"
          log "  PROCEED WITH WARNING: $SCOPE_WARNING"
          ;;
        skip:*)
          log "  SKIP: ${GATE_VERDICT#skip:}"
          handle_issue_failure "$ISSUE" "scope gate skip: ${GATE_VERDICT#skip:}" || break
          continue
          ;;
        blocker:*)
          log "  BLOCKER: ${GATE_VERDICT#blocker:}"
          handle_issue_failure "$ISSUE" "scope gate blocker: ${GATE_VERDICT#blocker:}" || break
          continue
          ;;
        *)
          log "  Unexpected verdict: '$GATE_VERDICT'. Proceeding."
          ;;
      esac
    fi
  fi

  # ── Phase 2: Implementation ───────────────────────────
  CURRENT_PHASE="implementation"
  write_status "running"
  log "[2/5] Implementation"
  IMPL_ID="impl-${ISSUE}-$(date +%s)"
  IMPL_HANDOFF="/tmp/${IMPL_ID}-handoff.md"
  IMPL_PROMPT_FILE="$LOG_DIR/${IMPL_ID}-prompt.md"

  generate_impl_prompt "$ISSUE" "$WORKTREE" "$BRANCH" "$IMPL_HANDOFF" "$SCOPE_WARNING" > "$IMPL_PROMPT_FILE"

  cd "$WORKTREE" || continue
  nohup pi --approve \
    --session-id "$IMPL_ID" \
    --skill "$IMPL_SKILL_PATH" \
    -p "@$IMPL_PROMPT_FILE" \
    > "$LOG_DIR/${IMPL_ID}.log" 2>&1 &
  IMPL_PID=$!
  CHILD_PIDS+=("$IMPL_PID")
  CURRENT_AGENT_PID="$IMPL_PID"
  write_status "running"
  log "  Agent PID $IMPL_PID (session: $IMPL_ID)"

  if ! wait_for_handoff "$IMPL_HANDOFF" "$TIMEOUT_IMPL" "$IMPL_PID"; then
    log "  ERROR: Timed out or died after ${TIMEOUT_IMPL}s."
    kill_agent "$IMPL_PID"
    handle_issue_failure "$ISSUE" "implementation timed out or died" || break
    continue
  fi
  log "  Done. Verifying local pre-PR CodeRabbit precheck..."
  if ! verify_local_coderabbit_precheck "$IMPL_HANDOFF"; then
    handle_issue_failure "$ISSUE" "local CodeRabbit precheck missing or failed" || break
    continue
  fi
  log "  Extracting PR number..."

  CURRENT_PR=$(extract_pr_number "$WORKTREE" "$IMPL_HANDOFF") || true
  if [ -z "$CURRENT_PR" ]; then
    log "  ERROR: No PR number found."
    handle_issue_failure "$ISSUE" "implementation did not produce a PR" || break
    continue
  fi
  log "  PR #$CURRENT_PR opened"
  write_status "running"

  # Control check between phases
  CTRL=$(check_control)
  if [ "$CTRL" = "skip" ]; then
    log "  SKIP received. PR #$CURRENT_PR left open."
    ISSUES_SKIPPED+=("$ISSUE")
    continue
  fi

  # ── Phase 3: Self-review ──────────────────────────────
  if [ "$SKIP_REVIEW" = "1" ]; then
    log "[3/5] Self-review: SKIPPED"
  else
    CURRENT_PHASE="self-review"
    write_status "running"
    log "[3/5] Self-review"
    REV_ID="review-${ISSUE}-$(date +%s)"
    REV_HANDOFF="/tmp/${REV_ID}-handoff.md"
    REV_PROMPT_FILE="$LOG_DIR/${REV_ID}-prompt.md"

    generate_review_prompt "$CURRENT_PR" "$WORKTREE" "$BRANCH" "$REV_HANDOFF" > "$REV_PROMPT_FILE"

    cd "$WORKTREE" || continue
    nohup pi --approve \
      --session-id "$REV_ID" \
      --skill "$REVIEW_SKILL_PATH" \
      -p "@$REV_PROMPT_FILE" \
      > "$LOG_DIR/${REV_ID}.log" 2>&1 &
    REV_PID=$!
    CHILD_PIDS+=("$REV_PID")
    CURRENT_AGENT_PID="$REV_PID"
    write_status "running"
    log "  Agent PID $REV_PID (session: $REV_ID)"

    if ! wait_for_handoff "$REV_HANDOFF" "$TIMEOUT_REVIEW" "$REV_PID"; then
      log "  WARNING: Timed out or died. Continuing."
      kill_agent "$REV_PID"
    else
      log "  Done"
    fi
  fi

  # Control check
  CTRL=$(check_control)
  if [ "$CTRL" = "skip" ]; then
    log "  SKIP received. PR #$CURRENT_PR left open."
    ISSUES_SKIPPED+=("$ISSUE")
    continue
  fi

  # ── Phase 4: Bot review ───────────────────────────────
  if [ "$SKIP_BOT" = "1" ]; then
    log "[4/5] Bot review: SKIPPED"
  else
    CURRENT_PHASE="bot-review"
    write_status "running"
    log "[4/5] Bot review via $AI_REVIEW_PROVIDER (max $REVIEW_LOOP_COUNT rounds)"
    BOT_ID="ai-pr-review-loop-${AI_REVIEW_PROVIDER}-${CURRENT_PR}-$(date +%s)"
    BOT_HANDOFF="/tmp/${BOT_ID}-handoff.md"
    BOT_PROMPT_FILE="$LOG_DIR/${BOT_ID}-prompt.md"

    generate_bot_prompt "$CURRENT_PR" "$WORKTREE" "$BOT_ID" "$BOT_HANDOFF" > "$BOT_PROMPT_FILE"

    cd "$WORKTREE" || continue
    nohup pi --approve \
      --session-id "$BOT_ID" \
      --skill "$BOT_SKILL_PATH" \
      -p "@$BOT_PROMPT_FILE" \
      > "$LOG_DIR/${BOT_ID}.log" 2>&1 &
    BOT_PID=$!
    CHILD_PIDS+=("$BOT_PID")
    CURRENT_AGENT_PID="$BOT_PID"
    write_status "running"
    log "  Agent PID $BOT_PID (session: $BOT_ID)"

    if ! wait_for_handoff "$BOT_HANDOFF" "$TIMEOUT_BOT" "$BOT_PID"; then
      log "  WARNING: Timed out or died. Attempting merge anyway."
      kill_agent "$BOT_PID"
    else
      log "  Done"
      # Check for explicit bot-review blockers. CI status is verified in the merge phase;
      # do not infer CI failure from free-form handoff prose such as "all green after retry".
      if grep -Eiq "Exit reason:.*blocker" "$BOT_HANDOFF" 2>/dev/null || \
        (grep -Eiq "Still blocked:" "$BOT_HANDOFF" 2>/dev/null && ! grep -Eiq "Still blocked:[[:space:]]*(none|0|zero|$)" "$BOT_HANDOFF" 2>/dev/null); then
        log "  Bot reports a review blocker. Skipping merge."
        handle_issue_failure "$ISSUE" "bot review reported a blocker" || break
        continue
      fi
    fi
  fi

  # ── Phase 5: Merge ───────────────────────────────────
  if [ "$NO_MERGE" = "1" ]; then
    log "[5/5] Merge: SKIPPED (NO_MERGE=1). PR #$CURRENT_PR ready."
    ISSUES_COMPLETED+=("$ISSUE")
    continue
  fi

  CURRENT_PHASE="merging"
  write_status "running"
  log "[5/5] Merge PR #$CURRENT_PR"
  cd "$REPO" || continue

  # Poll CI until complete
  CI_FAILURES=$(wait_for_ci "$CURRENT_PR" "$TIMEOUT_CI") || true

  if [ "$CI_FAILURES" = "0" ]; then
    # Draft PRs cannot be merged even when checks/reviews are green. Mark ready before merging.
    if [ "$(gh pr view "$CURRENT_PR" --json isDraft -q .isDraft 2>/dev/null || echo false)" = "true" ]; then
      log "  PR is draft; marking ready before merge"
      gh pr ready "$CURRENT_PR" 2>/dev/null || true
    fi

    # Remove worktree before merge so --delete-branch works
    cleanup_worktree "$WORKTREE"

    if gh pr merge "$CURRENT_PR" --"$MERGE_STRATEGY" --delete-branch --admin 2>/dev/null; then
      log "  Merged via gh CLI ✓"
    elif gh api "repos/$OWNER_REPO/pulls/$CURRENT_PR/merge" -X PUT \
        -f merge_method="$MERGE_STRATEGY" \
        -f commit_title="$(gh pr view "$CURRENT_PR" --json title -q .title) (#$CURRENT_PR)" 2>/dev/null; then
      log "  Merged via API ✓"
      gh api "repos/$OWNER_REPO/git/refs/heads/$BRANCH" -X DELETE 2>/dev/null || true
    else
      log "  ERROR: Merge failed."
      handle_issue_failure "$ISSUE" "merge failed" || break
      continue
    fi
  elif [ "$CI_FAILURES" = "timeout" ]; then
    log "  ERROR: CI timed out. Skipping merge."
    cleanup_worktree "$WORKTREE"
    handle_issue_failure "$ISSUE" "CI timed out" || break
    continue
  else
    log "  ERROR: CI has $CI_FAILURES failures. Skipping merge."
    cleanup_worktree "$WORKTREE"
    handle_issue_failure "$ISSUE" "CI has $CI_FAILURES failures" || break
    continue
  fi

  # Pull base branch for next issue
  cd "$REPO" || continue
  git fetch origin "$BASE_BRANCH" --quiet
  git pull origin "$BASE_BRANCH" --ff-only 2>/dev/null || true
  ISSUES_COMPLETED+=("$ISSUE")
  CURRENT_PHASE=""
  log "  Issue #$ISSUE done ✓"
  write_status "running"
  sleep 10
done

# ── Clean exit ───────────────────────────────────────────────────────────────
trap - INT TERM
write_status "$PIPELINE_TERMINAL_STATE"

log ""
log "═══════════════════════════════════════════════════════════════"
log "PIPELINE COMPLETE"
log "═══════════════════════════════════════════════════════════════"
log "Results:"
for issue in "${ISSUES_COMPLETED[@]:-}"; do
  [ -n "$issue" ] && log "  ✓ #$issue merged"
done
for issue in "${ISSUES_SKIPPED[@]:-}"; do
  [ -n "$issue" ] && log "  ✗ #$issue skipped"
done
log ""
log "${#ISSUES_COMPLETED[@]} merged, ${#ISSUES_SKIPPED[@]} skipped."
